name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
        cache: 'pip'

    - name: Build Executable
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: main.py
        standalone: true
        onefile: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }} Build
        path: |
          build/*.exe
          build/*.bin
          build/*.app/**/*

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.OTHER_GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: "🤫"
        draft: false
        prerelease: false

    - name: Upload executables
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.OTHER_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          build/*.exe
        asset_name: ${{ runner.os }}-build-${{ github.ref }}.${{ matrix.os == 'windows-latest' && 'exe' || matrix.os == 'macos-latest' && 'app' || 'bin' }}
        asset_content_type: application/octet-stream